name: PowerShell script
author: Freddy Kristiansen
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  getSecrets:
    description: Comma separated list of Secrets to get
    required: true
  parentTelemetryScopeJson:
    description: Specifies the parent telemetry scope for the telemetry signal
    required: false
    default: '7b7d'
runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      env:
        _getSecrets: ${{ inputs.getSecrets }}
        _parentTelemetryScopeJson: ${{ inputs.parentTelemetryScopeJson }}
      run: try { ${{ github.action_path }}/ReadSecrets.ps1 -getSecrets $ENV:_getSecrets -parentTelemetryScopeJson $ENV:_parentTelemetryScopeJson } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }
branding:
  icon: terminal
  color: blue
