name: PowerShell script
author: Freddy Kristiansen
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  gitHubSecrets:
    description: All GitHub Secrets in compressed JSON format
    required: true
  getSecrets:
    description: Comma separated list of Secrets to get
    required: true
outputs:
  Secrets:
    description: All requested secrets in compressed JSON format
    value: ${{ steps.ReadSecrets.outputs.Secrets }}
  TokenForCommits:
    description: The token to use when workflows are creating Pull Requests or Commits.
    value: ${{ steps.ReadSecrets.outputs.TokenForCommits }}
runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      id: ReadSecrets
      env:
        _getSecrets: ${{ inputs.getSecrets }}
      run: |
        $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
        try {
          ${{ github.action_path }}/ReadSecrets.ps1 -gitHubSecrets '${{ inputs.gitHubSecrets }}' -getSecrets $ENV:_getSecrets
        }
        catch {
          Write-Host "::ERROR::Unexpected error when running action. Error Message: $($_.Exception.Message.Replace("`r",'').Replace("`n",' ')), StackTrace: $($_.ScriptStackTrace.Replace("`r",'').Replace("`n",' <- '))";
          exit 1
        }
branding:
  icon: terminal
  color: blue
