name: PowerShell script
author: Freddy Kristiansen
inputs:
  settingsJson:
    description: Settings from template repository in compressed Json format
    required: false
    default: '{"keyVaultName": ""}'
  secrets:
    description: Comma separated list of Secrets to get
    required: true
  parentTelemetryScopeJson:
    description: Specifies the parent telemetry scope for the telemetry signal
    required: false
    default: '{}'
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/ReadSecrets.ps1 -settingsJson '${{ inputs.settingsJson }}' -secrets '${{ inputs.secrets }}' -parentTelemetryScopeJson '${{ inputs.parentTelemetryScopeJson }}'
      shell: PowerShell
branding:
  icon: terminal
  color: blue