name: Fetch Project dependencies
author: Microsoft Corporation
description: Fetches the dependencies of a project
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  project:
    description: Project for which to fetch dependencies
    required: true
  buildMode:
    description: Build mode used when building the artifacts
    required: true
  projectsDependenciesJson:
    description: A JSON object that matches eash project with its dependency projects
    required: true
  destinationPath:
    default: ${{ github.workspace }}/.dependencies
    description: The destination path where the dependencies will be stored
outputs:
  FetchedApps: 
    description: A JSON-formatted array of paths to .app files of the apps that were fetched
    value: ${{ steps.FetchDependencies.outputs.FetchedApps }}
  FetchedTestApps: 
    description: A JSON-formatted array of paths to .app files of the test apps that were fetched
    value: ${{ steps.FetchDependencies.outputs.FetchedTestApps }}
runs:
  using: composite
  steps:
    - name: Download artifacts from current build
      uses: actions/download-artifact@v3
      with:
        path: ${{ inputs.destinationPath}}

    - name: Fetch project dependencies
      shell: ${{ inputs.shell }}
      id: FetchDependencies
      env:
        gitHubToken: ${{ github.token }}
      run:
        ${{ github.action_path }}/FetchProjectDependencies.ps1 -project '${{ inputs.project }}' -buildMode '${{ inputs.buildMode }}' -projectsDependenciesJson '${{ inputs.projectsDependenciesJson }}' -baseBranch '${{ github.base_ref }}' -baseFolder '${{ github.workspace }}' -destinationPath '${{ inputs.destinationPath }}' -token '${{ github.token }}'
branding:
  icon: terminal
  color: blue
