name: Fetch Project dependencies
author: Microsoft Corporation
description: Fetches the dependencies of a project
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  project:
    description: Project for which to fetch dependencies
    required: true
  buildMode:
    description: Build mode used when building the artifacts
    required: true
  projectsDependenciesJson:
    description: A JSON object that matches eash project with its dependency projects
    required: true
  destinationPath:
    default: ${{ github.workspace }}/.dependencies
    description: The destination path where the dependencies will be stored
outputs:
  FetchedApps: 
    description: A JSON-formatted array of paths to .app files of the apps that were fetched
    value: ${{ steps.FetchDependencies.outputs.FetchedApps }}
  FetchedTestApps: 
    description: A JSON-formatted array of paths to .app files of the test apps that were fetched
    value: ${{ steps.FetchDependencies.outputs.FetchedTestApps }}
runs:
  using: composite
  steps:
    - name: Download artifacts from current build
      uses: actions/download-artifact@v3
      with:
        path: ${{ inputs.destinationPath}}

    - name: Fetch project dependencies
      shell: ${{ inputs.shell }}
      id: FetchDependencies
      env:
        _project: ${{ inputs.project }}
        _buildMode: ${{ inputs.buildMode }}
        _projectsDependenciesJson: ${{ inputs.projectsDependenciesJson }}
        _baseBranch: ${{ github.base_ref }}
        _baseFolder: ${{ github.workspace }}
        _destinationPath: ${{ inputs.destinationPath }}
        _gitHubToken: ${{ github.token }}
      run:
        ${{ github.action_path }}/FetchProjectDependencies.ps1 -project $ENV:_project -buildMode $ENV:_buildMode -projectsDependenciesJson $ENV:_projectsDependenciesJson -baseBranch $ENV:_baseBranch -baseFolder $ENV:_baseFolder -destinationPath $ENV:_destinationFolder -token $ENV:_gitHubToken
branding:
  icon: terminal
  color: blue
