name: 'Pull Request Handler'

on:
  pull_request_target:
    paths-ignore:
      - '**.md'
    branches: [ 'main' ]

defaults:
  run:
    shell: powershell

permissions:
  contents: read
  actions: read
  pull-requests: read

jobs:
  PullRequestHandler:
    runs-on: [ windows-latest ]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Determine Changed Files
        id: ChangedFiles
        run: |
          $ErrorActionPreference = "STOP"
          Set-StrictMode -version 2.0

          $headers = @{             
              "Authorization" = 'token ${{ secrets.GITHUB_TOKEN }}'
              "Accept" = "application/vnd.github.baptiste-preview+json"
          }
          $baseSHA = '${{ github.event.pull_request.base.sha }}'
          $headSHA = '${{ github.event.pull_request.head.sha }}'
          $url = "$($ENV:GITHUB_API_URL)/repos/$($ENV:GITHUB_REPOSITORY)/compare/$baseSHA...$headSHA"
          $response = Invoke-WebRequest -UseBasicParsing -Headers $headers -Uri $url | ConvertFrom-Json

          $location = (Get-Location).path
          $prfilesChanged = @()
          Write-Host "Files Changed:"
          $response.files | ForEach-Object {
            $filename = $_.filename
            $extension = [System.IO.Path]::GetExtension($filename)
            Write-Host "- $filename $_.status"
            if ('${{ github.event.pull_request.head.repo.full_name }}' -ne $ENV:GITHUB_REPOSITORY) {
              if ($extension -eq '.ps1' -or $extension -eq '.yaml' -or $extension -eq '.yml' -or $name -eq "CODEOWNERS") {
                throw "Pull Request containing changes to scripts, workflows or CODEOWNERS are not allowed from forks."
              }
            }
          }