name: 'Troubleshooting'

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  Troubleshooting:
    needs: [ ]
    runs-on: [ windows-latest ]
    steps:
      - name: Dump Workflow Information
        uses: microsoft/AL-Go-Actions/DumpWorkflowInfo@main
        with:
          shell: powershell

      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/TroubleShooting@main
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
