name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  Test:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3

      - name: Run Tests
        run: |
          . (Join-Path "." "Tests/runtests.ps1")

      - name: Test AL-GO Workflows
        if: github.repository_owner == 'microsoft'
        run: |
          $errorActionPreference = "Stop"
          try {
            Get-ChildItem -Path (Join-Path "." "Tests/WorkflowSanitation") -Filter "*.Test.ps1" -File | ForEach-Object {
              Write-Host "Running $($_.Name)"
              . $_.FullName
            }
          }
          catch {
            Write-Host "::Error::Error when running tests. The Error was $($_.Exception.Message)"
            $host.SetShouldExit(1)
          }
